CREATE TABLE TAB_PADRAO
(ID INT AUTO_INCREMENT,
DESCRITOR VARCHAR(20),
ENDERECO VARCHAR(100) NULL,
CIDADE VARCHAR(50) DEFAULT 'Rio de Janeiro',
DATA_CRIACAO TIMESTAMP DEFAULT current_timestamp(),
primary key (ID));

INSERT INTO TAB_PADRAO(
DESCRITOR, ENDERECO,
CIDADE, DATA_CRIACAO
) VALUES ('CLIENTE X', 'RUA PROJETADA A', 'São Paulo', '2019-01-01');

select * from TAB_PADRAO;

INSERT INTO TAB_PADRAO(
DESCRITOR
) VALUES ('CLIENTE Y');